### PR TITLE
Added an "API-Key" preference as a workaround

### PR DESCRIPTION
**Pull request by williamchange**
image

Added an API-Key field under the addon's preferences and tried to fix some warnings raised by Blender.

image
Can confirm it works and I can see updates in my wakatime account

### CODE REVIEW

**Review by yihuajack — APPROVED** [review]
It works fine with Blender 2.91.0 on Windows 10 20H2

**Comment by allista** [comment]
Thank you so much for your contribution! I'll merge it at first opportunity today evening.

**Comment by CL-mullins** [comment]
This hasn't been merged yet, how do I access it?

**Comment by williamchange** [comment]
For the meantime you can access the fixed [script](https://raw.githubusercontent.com/williamchange/WakatimeBlender/master/WakaTime.py) from my fork

**Comment by CL-mullins** [comment]
Thank you, I forked it, but not sure how to access my stats on WakaTime, do I need to edit meshes? The IDE description on WT doesn't give me that much to work with.

**Comment by williamchange** [comment]
> Thank you, I forked it, but not sure how to access my stats on WakaTime, do I need to edit meshes? The IDE description on WT doesn't give me that much to work with.

Just spend sometime in Blender working on a saved .blend file should give you some stats and they should show up in your "Dashboard" in WT

**Pull request merged**
